### ISSUE TITLE
"Azure Eventhub Client for C" samples links are broken

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-c#1]
_From @BretStateham on March 9, 2016 16:36_

The links to the "samples" folder, and the various platform samples (Beaglebone Black, Fedora Linux, Ubuntu Linux, etc.) are broken on the https://github.com/Azure/azure-event-hubs/blob/master/c/README.md.  Looks like they have all moved to the "docs" folder https://github.com/Azure/azure-event-hubs/tree/master/c/docs 

_Copied from original issue: Azure/azure-event-hubs#86_

**Comment by mrohera** [comment]
This has been fixed. Thank you for pointing this out.
