### ISSUE TITLE
SendBatch: partitionKey is always "sender"

### ISSUE THREAD

**Issue by alepez** [Azure/azure-event-hubs-c#13]
Every EventData sent with a Batch has partitionKey "sender" in the EventHub.

How to reproduce: using the provided sample "send_batch", change connectionString with something valid. Run the sample. Inspect arrived events (e.g.: with https://github.com/paolosalvatori/ServiceBusExplorer). Actual partitionKey is `sender`, expected is `PartitionKeyInfo` (this is the string provided in the sample).

**Comment by dcristoloveanu** [comment]
@alepez 

I will have a look at this issue, it sounds like a bug to me.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
@alepez 

I have a temporary fix in the optional_publisherid branch. Updating unittests and then it shall go to master.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
@alepez 

The fix for this has been checked in to master.
I will close the issue now, feel free to open a new one if you have more issues around this.

Thanks,
/Dan
