### ISSUE TITLE
The instruction link in README.md file is invalid

### ISSUE THREAD

**Issue by micli** [Azure/azure-event-hubs-c#19]
The content of file:
https://github.com/Azure/azure-event-hubs-c/blob/master/eventhub_client/samples/receive/readme.md
contains a instructions link 'Follow the instructions here.' which is points to https://github.com/Azure/azure-event-hubs/tree/master/c.

The link has been invalid for a long time.

**Comment by dcristoloveanu** [comment]
Hi @micli 
There are several documentation updates that need to be made (for example the readme at root is rather outdated).
I fixed the link in question for now (and the ones for the other samples), but I will leave this issue open until the doc updates are made.

Cheers,
/Dan

**Comment by micli** [comment]
Close it, due to it has been fixed.
