### ISSUE TITLE
Allow senders to set partition id.

### ISSUE THREAD

**Issue by piotrzaremba** [Azure/azure-event-hubs-c#5]
Allow a sender to sent the partition id for a particular event hub.

**Comment by piotrzaremba** [comment]
I may have fixed my own problem.  Correct me if I am wrong.  In the send.c example the following string will give me direct partition access.

static const char* eventHubPath = "{eventHubName}/Partition/{partitionNumber}";

**Comment by dcristoloveanu** [comment]
Hi @piotrzaremba,

Sorry for the huge delay on this. That is correct, you can definitely access a specific partition like that if all your sends for one instance are supposed to go to one partition.

If you want to send specific messages to different partitions over the same sender, that is not yet supported in the C SDK. We'll consider that in the future.

I will close this issue.

Thanks,
/Dan
